[package]
name = "git-ai"
version = "0.2.6"
edition = "2021"
description = "Git AI: Automates commit messages using ChatGPT. Stage your files, and Git AI generates the messages."
license = "MIT"
repository = "https://github.com/oleander/git-ai"

[lib]
name = "ai"
test = true

[[bin]]
name = "git-ai"
path = "src/main.rs"

[[bin]]
name = "git-ai-hook"
path = "src/bin/hook.rs"

[dependencies]
anyhow = { version = "1.0.86", default-features = false }
async-openai = { version = "0.18.3", default-features = false }
colored = "2.1.0"
config = { version = "0.13.4", default-features = false, features = ["ini"] }
console = { version = "0.15.8", default-features = false }
ctrlc = "3.4.4"
dotenv = "0.15.0"
env_logger = { version = "0.10.2", default-features = false }
git2 = { version = "0.18.3", default-features = false }
home = "0.5.9"
indicatif = { version = "0.17.8", default-features = false }
lazy_static = "1.4.0"
log = "0.4.21"
reqwest = { version = "0.11.27", default-features = true }
serde = { version = "1", default-features = false }
serde_derive = "1.0.203"
serde_ini = "0.2.0"
serde_json = "1.0.117"
structopt = "0.3.26"
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["rt-multi-thread"] }
tiktoken-rs = { version = "0.5.9" }
ollama-rs = "0.2.0"

[dev-dependencies]
tempfile = "3.10.1"
anyhow = { version = "1.0.86", default-features = false }
git2 = { version = "0.18.3", default-features = false }
rand = { version = "0.8.5", default-features = false }

[profile.release]
codegen-units = 1
opt-level = 3
debug = true
lto = true

[profile.release.package."*"]
codegen-units = 1
opt-level = 3
