cargo-features = ["edition2024"]

[package]
name = "git-ai"
version = "0.1.20"
edition = "2024"
description = "Git AI: Automates commit messages using ChatGPT. Stage your files, and Git AI generates the messages."
license = "MIT"

[lib]
name = "ai"
test = true

[[bin]]
name = "git-ai"
path = "src/main.rs"

[[bin]]
name = "git-ai-hook"
path = "src/bin/hook.rs"

[[bin]]
name = "git-ai-clear"
path = "src/bin/clear.rs"

[dependencies.clap]
features = ["derive", "wrap_help"]
default-features = true
version = "4.5.2"

[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
reqwest = { version = "0.11.24", features = ["json"] }
serde = { version = "1", features = ["derive"] }
dotenv_codegen = "0.15.0"
serde_derive = "1.0.197"
async-openai = "0.18.3"
serde_json = "1.0.114"
env_logger = "0.10.2"
lazy_static = "1.4.0"
thiserror = "1.0.57"
indicatif = "0.17.8"
serde_ini = "0.2.0"
console = "0.15.8"
anyhow = "1.0.80"
dotenv = "0.15.0"
config = "0.13.4"
colored = "2.1.0"
ctrlc = "3.4.2"
log = "0.4.21"
home = "0.5.9"
indicatif-log-bridge = "0.2.2"
termion = "3.0.0"
crossterm = "0.27.0"

[dependencies.git2]
default-features = false
version = "0.18.2"

[dev-dependencies]
tempfile = "3.10.1"
anyhow = "1.0.80"
git2 = "0.18.2"
rand = "0.8.5"

[profile.release]
codegen-units = 1
opt-level = 3
debug = true
lto = true

[profile.release.package."*"]
codegen-units = 1
opt-level = 3
