[package]
name = "git-ai"
version = "0.1.9"
edition = "2021"
description = "Git AI: Automates commit messages using ChatGPT. Stage your files, and Git AI generates the messages."
license = "MIT"

[lib]
name = "ai"
test = true

[[bin]]
name = "git-ai"
path = "src/main.rs"

[[bin]]
name = "git-ai-hook"
path = "src/bin/hook.rs"

[dependencies.clap]
features = ["derive", "wrap_help"]
default-features = true
version = "4.4.11"

[dependencies]
tokio = { version = "1.35.0", features = ["macros", "rt-multi-thread"] }
reqwest = { version = "0.11.22", features = ["json"] }
serde = { version = "1", features = ["derive"] }
dotenv_codegen = "0.15.0"
serde_derive = "1.0.193"
serde_json = "1.0.108"
env_logger = "0.10.1"
lazy_static = "1.4.0"
thiserror = "1.0.51"
indicatif = "0.17.7"
serde_ini = "0.2.0"
console = "0.15.7"
anyhow = "1.0.75"
dotenv = "0.15.0"
config = "0.13.4"
ctrlc = "3.4.1"
log = "0.4.20"
home = "0.5.9"

[dependencies.git2]
default-features = false
version = "0.18.1"

[dev-dependencies]
tempfile = "3.8.1"
anyhow = "1.0.75"
git2 = "0.18.1"
rand = "0.8.5"

[profile.release]
codegen-units = 1
opt-level = 3
debug = true
lto = true

[profile.dev.package."*"]
codegen-units = 1
opt-level = 3
