[package]
name = "git-ai"
version = "0.1.38"
edition = "2021"
description = "Git AI: Automates commit messages using ChatGPT. Stage your files, and Git AI generates the messages."
license = "MIT"
repository = "https://github.com/oleander/git-ai"

[lib]
name = "ai"
test = true

[[bin]]
name = "git-ai"
path = "src/main.rs"

[[bin]]
name = "git-ai-hook"
path = "src/bin/hook.rs"

[dependencies]
anyhow = "1.0.86"
async-openai = "0.18.3"
colored = "2.1.0"
config = "0.13.4"
console = "0.15.8"
ctrlc = "3.4.4"
dotenv = "0.15.0"
env_logger = "0.10.2"
git2 = { version = "0.18.3" }
home = "0.5.9"
indicatif = "0.17.8"
lazy_static = "1.4.0"
log = "0.4.21"
reqwest = { version = "0.11.27", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_derive = "1.0.203"
serde_ini = "0.2.0"
serde_json = "1.0.117"
structopt = { version = "0.3.26", features = ["color", "suggestions"] }
thiserror = "1.0.61"
tokio = { version = "1.37.0", features = ["rt-multi-thread", "macros"] }
tiktoken-rs = { version = "0.5.8" }

[dev-dependencies]
tempfile = "3.10.1"
anyhow = "1.0.86"
git2 = "0.18.3"
rand = "0.8.5"

[profile.release]
codegen-units = 1
opt-level = 3
debug = true
lto = true

[profile.release.package."*"]
codegen-units = 1
opt-level = 3
