FROM rust:1.84

WORKDIR /app

RUN apt-get update && \
    apt-get install -y pkg-config libssl-dev perl make && \
    rm -rf /var/lib/apt/lists/*

RUN cargo install sccache
ENV SCCACHE_DIR=/sccache
VOLUME /sccache
RUN sccache --start-server
RUN export RUSTC_WRAPPER=sccache

COPY Cargo.toml Cargo.lock ./
RUN mkdir -p src/bin
RUN echo "fn main() {}" > src/lib.rs
RUN echo "fn main() {}" > src/main.rs
RUN echo "fn main() {}" > src/bin/hook.rs
RUN cargo fetch
RUN cargo build
RUN cargo install --path . --debug

COPY . ./
RUN cargo install --path . --debug

RUN curl -fsSL https://ollama.com/install.sh | sh
RUN ollama start &
RUN while ! ollama ls; do sleep 1; done
RUN ollama pull smollm:135m

CMD ["git-ai", "--help"]
