[tasks.secret]
command = "touch"
args = [".secrets"]
files_not_exist = [".secrets"]

[tasks.integration]
command = "fish"
args = ["./scripts/integration-tests"]
dependencies = ["secret"]
env_files = [".secrets"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.check]
command = "cargo"
args = ["clippy", "--", "-D", "warnings"]
dependencies = ["clean"]

[tasks.udeps]
install_crate = "cargo-udeps"
command = "cargo"
args = ["udeps", "--all-targets"]

[tasks.bump-version]
install_crate = "cargo-bump"
command = "cargo"
args = ["bump", "patch", "--git-tag"]
condition = { env_set = ["CI"] }

[tasks.publish]
command = "cargo"
args = ["publish"]
dependencies = ["verify", "bump-version"]

[tasks.verify]
run_task = { name = ["format", "check", "test", "integration", "udeps"] , parallel = true }

# ----------

[tasks.ci]
dependencies = ["build", "verify"]

[tasks.release]
command = "git"
args = ["push", "origin", "HEAD", "--tags"]
dependencies = ["publish"]
