openapi: 3.1.0
info:
  title: OpenAI API Mock
  version: 1.0.0
paths:
  /v1/chat/completions:
    post:
      operationId: createChatCompletion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - model
                - messages
              properties:
                model:
                  type: string
                messages:
                  type: array
                  items:
                    type: object
                    required:
                      - role
                      - content
                    properties:
                      role:
                        type: string
                        enum: ["system", "user", "assistant"]
                      content:
                        type: string
                max_tokens:
                  type: integer
                temperature:
                  type: number
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                  - object
                  - created
                  - model
                  - choices
                properties:
                  id:
                    type: string
                  object:
                    type: string
                    const: "chat.completion"
                  created:
                    type: integer
                  model:
                    type: string
                  choices:
                    type: array
                    minItems: 1
                    items:
                      type: object
                      required:
                        - index
                        - message
                        - finish_reason
                      properties:
                        index:
                          type: integer
                        message:
                          type: object
                          required:
                            - role
                            - content
                          properties:
                            role:
                              type: string
                              const: "assistant"
                            content:
                              type: string
                        finish_reason:
                          type: string
                          enum: ["stop"]
                  usage:
                    type: object
                    required:
                      - prompt_tokens
                      - completion_tokens
                      - total_tokens
                    properties:
                      prompt_tokens:
                        type: integer
                      completion_tokens:
                        type: integer
                      total_tokens:
                        type: integer
              examples:
                default:
                  value:
                    id: "chatcmpl-123"
                    object: "chat.completion"
                    created: 1677652288
                    model: "gpt-4"
                    choices:
                      - index: 0
                        message:
                          role: "assistant"
                          content: "This is a mock response"
                        finish_reason: "stop"
                    usage:
                      prompt_tokens: 0
                      completion_tokens: 0
                      total_tokens: 0
