#!/usr/bin/env fish

set -x fish_trace 1

if not test -n "$OPENAI_API_KEY"
    echo "Please set the OPENAI_API_KEY environment variable."
    exit 1
end

if not command -v cargo
    echo "Cargo not found. Please install Rust."
    exit 1
end

function on_exit --on-event fish_exit
    if test -d $DIR
        rm -rf $DIR
    end
end

set DIR /tmp/git-ai-test

cargo install --debug --path .

rm -rf $DIR
mkdir $DIR
cd $DIR

git init
git config user.name "Test User"
git config user.email "hello@world.com"
git config --global init.defaultBranch main
git branch -m main

git-ai hook
git-ai hook install || exit 1
git-ai hook uninstall || exit 1
git-ai hook install || exit 1
git-ai hook reinstall || exit 1

echo "Hello World 0" >README.md
git add README.md
git commit --no-edit || exit 1
git status --porcelain || exit 1

git-ai config
git-ai config set
git-ai config set model gpt-4 || exit 1
git-ai config set max-tokens 512 || exit 1
git-ai config set max-commit-length 1024 || exit 1
git-ai config set openai-api-key "$OPENAI_API_KEY" || exit 1

echo "Hello World" >README.md
git add README.md
git commit -m "Initial commit" || exit 1

echo "Hello World 2" >README.md
git add README.md
git commit --no-edit || exit 1
git commit --amend --no-edit || exit 1
git status --porcelain || exit 1
