name: Bump Version

on:
  push:
    branches:
      - main

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup environment
        run: |
          git config user.name "Linus Oleander"
          git config user.email "oleander@users.noreply.github.com"
          cargo install cargo-bump --force

      - name: Install cargo-bump
        run: cargo install cargo-bump --force

      - name: Bump version
        run: cargo bump patch --git-tag

      - name: Push to GitHub
        run: git push origin HEAD --tags
