name: Bump Version

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git
        run: |
          git config user.name "Linus Oleander"
          git config user.email "oleander@users.noreply.github.com"

      - name: Install cargo-bump
        run: cargo install cargo-bump --force

      - name: Bump version
        run: |
          git stash || true
          cargo bump patch --git-tag
          git commit -a --amend --no-edit || true

      - name: Push to GitHub
        run: git push origin HEAD --tags
