name: CD

on:
  push:
    tags:
      - v*
env:
  CARGO_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ env.CARGO_TOKEN }}
