name: CD

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  # TARGET: x86_64-apple-darwin
  TARGET: aarch64-unknown-linux-gnu
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config user.name "Linus Oleander"
          git config user.email "oleander@users.noreply.github.com"

      - name: Cache target and cargo build
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup/toolchains/
            target/
          key: ${{ runner.os }}-rustup-cargo-${{ env.TARGET }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rustup-cargo-${{ env.TARGET }}-

      # - name: Add target (${{ env.TARGET }})
      #   run: rustup target add ${{ env.TARGET }}

      - name: Install cargo-bump
        run: cargo install cargo-bump

      - name: Ensure no changes
        continue-on-error: true
        run: git diff --exit-code --quiet && cargo check

      - name: Git status
        if: failure()
        run: git status && exit 1

      - name: Bump version
        run: cargo bump patch --git-tag || git status

      - name: Get the latest tag
        id: version
        run: git describe --tags --abbrev=0 HEAD

      - name: Include the version bump in the commit message
        run: git commit -a --amend --no-edit

      # - name: Publish to crates.io
      #   run: cargo publish --allow-dirty --dry-run

      - name: Build for target (${{ env.TARGET }})
        run: cargo build -Z unstable-options --profile dev --artifact-dir bin --target ${{ env.TARGET }}

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: v${{ steps.version.outputs.version }}-${{ runner.os }}
          path: bin/{git-ai,git-ai-hook}
          if-no-files-found: error
          overwrite: true

      - name: Push to origin
        run: git push origin HEAD
