name: CD

on:
  push:
    branches: [trigger]
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  actions: write
  packages: write

env:
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  ACTIONS_RUNTIME_TOKEN: dummy
  CARGO_TERM_COLOR: always

jobs:
  # Version bump and tag creation on main push
  #
  # On: Push to main
  # Do: 1. Bump version using cargo-bump
  #     2. Push to tag and changes to main
  version-bump:
    if: github.ref == 'refs/heads/trigger' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Configure git
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com

      - name: Install cargo-bump
        run: cargo install cargo-bump

      - name: Bump version and create tag
        run: |
          cargo bump patch --git-tag
          git commit -a --amend --no-edit
          git push origin HEAD --tags
