name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Setup nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy

      - name: Run clippy
        run: cargo clippy -- -D warnings

      - name: Run cargo fmt
        run: cargo fmt -- --check

  test:
    needs: lint
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest]
        rust: [nightly, stable]
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    steps:
      - uses: actions/checkout@v5
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Set up Rust (nightly)
        if: matrix.rust == 'nightly'
        uses: dtolnay/rust-toolchain@nightly
        
      - name: Set up Rust (stable)
        if: matrix.rust == 'stable'
        uses: dtolnay/rust-toolchain@stable

      - name: Install fish (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt update && sudo apt install -y fish

      - name: Install fish (macOS)
        if: startsWith(matrix.os, 'macos')
        run: brew install fish

      - name: Run integration tests
        if: env.OPENAI_API_KEY != ''
        run: fish ./scripts/integration-tests
        
      - name: Skip integration tests (no API key)
        if: env.OPENAI_API_KEY == ''
        run: echo "Skipping integration tests - no OPENAI_API_KEY configured"

      - name: Run cargo test
        run: cargo test
