name: Crate

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rust-std
          profile: minimal

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-crate-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-crate-

      - name: Setup git
        run: |
          git config user.name "Linus Oleander"
          git config user.email "oleander@users.noreply.github.com"

      - name: Setup cargo-bump
        continue-on-error: true
        run: cargo install cargo-bump

      - name: Bump version
        run: cargo bump patch --git-tag

      - name: Release to crates.io
        run: cargo publish

      - name: Release to GitHub
        run: git push origin HEAD --tags
