name: Build and Precompile Binaries

on:
  push:
    branches:
      - main
      - oleander-patch-1

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-x86:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Build for x86_64-unknown-linux-gnu
        run: |
          rustup target add x86_64-unknown-linux-gnu
          cargo build --release --target x86_64-unknown-linux-gnu

      - name: Install cargo-binstall
        run: cargo install cargo-binstall

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries-x86_64
          path: target/x86_64-unknown-linux-gnu/release/

  build-arm:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Build for aarch64-apple-darwin
        run: |
          rustup target add aarch64-apple-darwin
          cargo build --release --target aarch64-apple-darwin

      - name: Install cargo-binstall
        run: cargo install cargo-binstall

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries-arm
          path: target/aarch64-apple-darwin/release/
