name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  MAX_LENGTH: 100
  MAX_CHARS: 5000
  LANGUAGE: "en"
  TIMEOUT: 30

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - run: |
            git config --global user.name "John Doe"
            git config --global user.email "hello@example.com"
      - name: Run tests
        run: make install
