name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  APP_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        toolchain: [nightly, stable]
    steps:
      - uses: actions/checkout@v3
      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.os }}-cargo-${{ matrix.toolchain }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          default: true
          profile: minimal
          components: rustfmt,clippy
      - name: Build git-ai-hook
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --bin git-ai-hook
      - name: Install git-ai
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --path . --bin git-ai
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Rust fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Rust clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all -- --deny warnings
      - name: Test install hook
        run: git ai hook install
      - name: Git ai config
        run: git ai config set openai-api-key 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
      - name: Test simulate
        run: ./simulate.sh
