name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  MAX_LENGTH: 100
  MAX_CHARS: 5000
  LANGUAGE: "en"
  TIMEOUT: 30

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --bin git-ai-hook --no-default-features
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: --path . --bin git-ai --no-default-features
      - run: git ai install
